### ISSUE TITLE
PyVista TypeError: SetSpacing argument

### ISSUE THREAD

**Issue by Camkash** [pyvista/pyvista-support#140]
I have also posted this issue on StackOverflow.
https://stackoverflow.com/questions/60737919/pyvista-typeerror-setspacing-argument

I previously ran the following with no issues.

```
grid=pv.UniformGrid()
grid.points=np.array([x_surf,y_surf,z_surf]).transpose()
```

Today, I ran it and received the following. I have already tried reinstalling the package.

```
Traceback (most recent call last):

  File "C:\Users\camramez\Documents\Meshing\gen_terrain.py", line 28, in <module>
    grid.points=np.array([x_surf,y_surf,z_surf]).transpose()

  File "C:\ProgramData\Anaconda3\envs\mesh\lib\site-packages\pyvista\core\grid.py", line 470, in points
    self._from_specs((nx,ny,nz), (dx,dy,dz), (ox,oy,oz))

  File "C:\ProgramData\Anaconda3\envs\mesh\lib\site-packages\pyvista\core\grid.py", line 435, in _from_specs
    self.SetSpacing(xs, ys, zs)

TypeError: SetSpacing argument %Id: %V
```

The SetSpacing function on its own works fine. I have done the following as a quick fix, which works, but it does not technically solve the error.

```
try:
    grid.points=np.array([x_surf,y_surf,z_surf]).transpose()
except:
    1
```

**Comment by GuillaumeFavelier** [comment]
Hello @Camkash, so if I understand correctly you get the expected result with `SetSpacing` but it throws this `TypeError`. Could you check the type of the `_surf` variables or the `dtype` of your `numpy` array? I looked at the documentation and it seems that `_from_specs` expects `float` for `spacing`:

https://github.com/pyvista/pyvista/blob/master/pyvista/core/grid.py#L411-L429

Also I can't reproduce the issue on `master`, could you provide a minimal example?

If this a regression, we will work on it.

**Comment by Camkash** [comment]
Hello! 
type(x_surf) is a numpy.ndarray
type(x_surf[0,0]) is numpy.int32

I checked the code and it gives a default value for spacing as [1.0,1.0,1.0]. I tried making my _surf values into dtype=float and it gave the same error.

I haven't changed any pyvista code nor have I specified a spacing in my code!

**Comment by GuillaumeFavelier** [comment]
Thanks for the fast answer, I'll investigate further then. Which version of pyvista do you use? The version 0.24 got released very recently.

**Comment by Camkash** [comment]
It says 
- pyvista 0.24.0
- vtk 8.2.0
- scooby 0.5.2

I installed it from here:
https://anaconda.org/conda-forge/pyvista

I re-installed it today and still got the same error.
