### ISSUE TITLE
Dynamics camera postion in interactive mode

### ISSUE THREAD

**Issue by changliao1025** [pyvista/pyvista-support#158]
Finding a nice camera position is critical to view some 3D datasets. However, it is not easy to find one in most cases.
If the camera position can be viewed in real-time in the interactive mode, it might be helpful for us to design a protocol to generate a list of views to find the best position.

Can anyone share this type of function or code?

**Comment by GuillaumeFavelier** [comment]
Hm... The camera toolbar of the `BackgroundPlotter` is a great tool for that. You can save camera positions, edit and load them to your heart's content.

But I would not know where to start to automate this process if that's what you mean. Maybe defining what would be the 'best position' could help already?

IMO, the best camera setting should ensure good lighting on the central objects of the scene (heuristic for where the viewer focus is) or a given target object in particular. It should also limit the clutter (obstruction of the target object) and maximize the details (compromise over distance to focal point and area of the projection in the window space). You could refine this depending on what you want to achieve with the dataset and translate that programmatically I suppose.

**Comment by banesullivan** [comment]
The camera position is accessible in real-time as you plot via the `camera_position` property, you just need to either set up a background thread, use a callback with a key/click event in PyVista, or a custom event handler in VT to print/display that camera position tuple. However, I cannot imagine a human would gain any insight from reading those numerical values...

Here is some code to print the camera position anytime the camera is done moving:

```py
import pyvista as pv
from pyvista import examples
import vtk

mesh = examples.load_airplane()

plotter = pv.Plotter(notebook=False)
plotter.add_mesh(mesh)

def my_cpos_callback(*args):
    plotter.add_text(str(plotter.camera_position), name="cpos")
    return

plotter.iren.AddObserver(vtk.vtkCommand.EndInteractionEvent, my_cpos_callback)

plotter.show()
```

**Comment by anbai106** [comment]
> The camera position is accessible in real-time as you plot via the `camera_position` property, you just need to either set up a background thread, use a callback with a key/click event in PyVista, or a custom event handler in VT to print/display that camera position tuple. However, I cannot imagine a human would gain any insight from reading those numerical values...
> 
> Here is some code to print the camera position anytime the camera is done moving:
> 
> ```python
> import pyvista as pv
> from pyvista import examples
> import vtk
> 
> mesh = examples.load_airplane()
> 
> plotter = pv.Plotter(notebook=False)
> plotter.add_mesh(mesh)
> 
> def my_cpos_callback(*args):
>     plotter.add_text(str(plotter.camera_position), name="cpos")
>     return
> 
> plotter.iren.AddObserver(vtk.vtkCommand.EndInteractionEvent, my_cpos_callback)
> 
> plotter.show()
> ```

@banesullivan 
The code that you offered gave me this error:
`Traceback (most recent call last):
  File "<input>", line 14, in <module>
AttributeError: 'RenderWindowInteractor' object has no attribute 'AddObserver'`

**Comment by bibbygoodwin** [comment]
For others encountering this problem after coming here:
> The code that you offered gave me this error: `Traceback (most recent call last): File "<input>", line 14, in <module> AttributeError: 'RenderWindowInteractor' object has no attribute 'AddObserver'`

I had the same thing, I think it's just different APIs for different pyvista versions? (I'm on 0.37.0).

Replace `plotter.iren.AddObserver` with `plotter.iren.add_observer` and you should be good to go!
