### ISSUE TITLE
Animate streamlines

### ISSUE THREAD

**Issue by mcgoldba** [pyvista/pyvista-support#289]
Hi,

I am attempting to create a gif of animated streamlines that would show only a section of each streamline geometry travelling along the path of the streamline.

I figured this should be possible by generating the streamlines, and then iteratively applying a threshold filter to the streamlines for varying values of 'IntegrationTime'.  However, this gives me an "Empty mesh" error when I try to generate the gif.  What is the issue here?

As an example, the following code give me the error:

```py
import pyvista as pv
from pyvista import examples
import numpy as np

pv.set_plot_theme('doc')

mesh = examples.download_kitchen()
furniture = examples.download_kitchen(split=True)

arr = np.linalg.norm(mesh['velocity'], axis=1)
clim = [arr.min(), arr.max()]

p = pv.Plotter()
p.add_mesh(furniture, name='furniture', color=True)
p.add_mesh(mesh.outline(), color='black')
p.add_axes()

points = [(0.3133218396043338, 2.7124684588348242, -0.1295403008931934),
          (6.141497065501868, 4.360221085241634, 1.1320318482460088)]

streamlines = mesh.streamlines(n_points=10, max_steps=100,
                            pointa=points[0], pointb=points[1],
                            integration_direction='forward')

p.add_mesh(streamlines, color='grey', show_scalar_bar=False)

p.open_gif("streamlines.gif")

p.show(auto_close=False)

it_range = streamlines.get_data_range(arr='IntegrationTime')
print(it_range)
nframes = 25
it_delta = 10
for it in np.linspace(it_range[0], it_range[1], nframes+1)[:nframes]:
    itMin = it-it_delta if it-it_delta > it_range[0] else it_range[0]
    itMax = it+it_delta if it+it_delta < it_range[1] else it_range[1]

    p.add_mesh(
        streamlines.threshold(value=[itMin,itMax],scalars='IntegrationTime'),
        clim=clim, name='streamlines_threshold',
        line_width=5, render_lines_as_tubes=True
    )

    p.write_frame()
    
p.close()

```

and the error this code returns is:

```py
Traceback (most recent call last):
  File ".\pyVistaStreamlineGif.py", line 42, in <module>
    line_width=5, render_lines_as_tubes=True
  File "C:\...\site-packages\pyvista\plotting\plotting.py", line 1478, in add_mesh
    raise ValueError('Empty meshes cannot be plotted. Input mesh has zero points.')
ValueError: Empty meshes cannot be plotted. Input mesh has zero points.
```
I have tried many variations of setting for the `threshold` filter, as well as different setting for the streamline length, `it_delta`, however I always get the same error... unless `it_delta` is set to a very large value that encompasses the entire streamline (i.e. `it_delta=1000`.  However, this just shows me the whole streamline, which is of no differet than just plotting the streamlines.

![image](https://user-images.githubusercontent.com/50269816/99124126-9567d500-25cf-11eb-9f11-2c53d07c70ac.png)

**Comment by akaszynski** [comment]
Looks like `threshold` has `all_scalars=True` as default, which seems counterintuitive to me.

```py
import pyvista as pv
from pyvista import examples
import numpy as np

pv.set_plot_theme('doc')

mesh = examples.download_kitchen()
furniture = examples.download_kitchen(split=True)

arr = np.linalg.norm(mesh['velocity'], axis=1)
clim = [arr.min(), arr.max()]

p = pv.Plotter()
p.add_mesh(furniture, name='furniture', color=True)
p.add_mesh(mesh.outline(), color='black')
p.add_axes()

points = [(0.3133218396043338, 2.7124684588348242, -0.1295403008931934),
          (6.141497065501868, 4.360221085241634, 1.1320318482460088)]

streamlines = mesh.streamlines(n_points=10, max_steps=100,
                               pointa=points[0], pointb=points[1],
                               integration_direction='forward')

actor = p.add_mesh(streamlines, color='grey', show_scalar_bar=False)

p.open_gif("streamlines.gif")

p.show(auto_close=False)

scalars = 'velocity'
it_range = streamlines.get_data_range(arr=scalars)
print(it_range)
nframes = 50
it_delta = 0.001

# streamlines.threshold(value=[itMin, itMax], scalars='IntegrationTime')

for it in np.linspace(it_range[0], it_range[1], nframes+1)[:nframes]:
    itMin = it-it_delta if it-it_delta > it_range[0] else it_range[0]
    itMax = it+it_delta if it+it_delta < it_range[1] else it_range[1]


    mesh = streamlines.threshold(value=[itMin, itMax],
                                 scalars=scalars,
                                 all_scalars=False)
    if not mesh.n_points:
        continue

    actor = p.add_mesh(
        mesh,
        clim=clim, name='streamlines_threshold',
        line_width=5, render_lines_as_tubes=True
    )

    p.write_frame()

p.close()
```

![streamlines](https://user-images.githubusercontent.com/11981631/99129954-3b194500-25cc-11eb-9dcd-5464da19a506.gif)

**Comment by mcgoldba** [comment]
I have been able to generate this gif using a different method, though I am not sure if it is the best way.  After generating the streamlines  `split_bodies()` is used to return each streamline as a block within a `MultiBlockDataset`.  Then for each streamline, a certain number of points are extracted based on index, and these points are used to generate a `pv.Spline`, with a `tube` filter applied.

This generates moving sections of the streamlines in the gif, but all streeamlines progress at the same speed since it is just based on the array index.  Ideally, the rate that the streamline progresses would be based on the velocity. 

Here is my code:

```py
import pyvista as pv
from pyvista import examples
import numpy as np

pv.set_plot_theme('doc')

mesh = examples.download_kitchen()
furniture = examples.download_kitchen(split=True)

arr = np.linalg.norm(mesh['velocity'], axis=1)
clim = [arr.min(), arr.max()]

p = pv.Plotter()
p.add_mesh(furniture, name='furniture', color=True)
p.add_mesh(mesh.outline(), color='black')
p.add_axes()

points = [(0.3133218396043338, 2.7124684588348242, -0.1295403008931934),
          (6.141497065501868, 4.360221085241634, 1.1320318482460088)]

streamlines = mesh.streamlines(n_points=10, max_steps=100,
                            pointa=points[0], pointb=points[1],
                            integration_direction='forward')

split_streamlines = streamlines.split_bodies()

p.add_mesh(streamlines, color='grey', show_scalar_bar=False)

p.open_gif("streamlines.gif")

p.show(auto_close=False)

nframes = 25
npoints = 10
for i in range(nframes):

    for s in range(split_streamlines.n_blocks):

        streamline = split_streamlines.get(s)

        pMin = int(streamline.n_points/nframes*i)
        pMax = min(streamline.n_points, pMin+npoints)

        spline = pv.Spline(streamline.points[pMin:pMax], n_points=pMax-pMin)
        spline['velocity'] = streamline['velocity'][pMin:pMax]
        tube = spline.tube(radius=0.02)

        p.add_mesh(tube, clim=clim, name='streamlines_threshold_'+str(s),
                   scalars='velocity', line_width=1, render_lines_as_tubes=True
            )

    p.write_frame()


p.close()


```

and the resulting gif:

![streamlines](https://user-images.githubusercontent.com/50269816/99130146-8720b580-25dd-11eb-883c-f135e0f4ef64.gif)

**Comment by mcgoldba** [comment]
Thanks @akaszynski .  As you can see from my last post, I tried a different route, but I will experiment with the `all_scalars` setting when I get back to my computer

**Comment by mcgoldba** [comment]
@akaszynski.  I was unable to come up with a good solution using threshold.  I am able to get the streamlines to appear just as you with `all_scalars=False`, but it seems that the threshold is still not applied to the `IntegrationTime` correctly.

However, I was able to get it to work using `clip_scalar`.   I think maybe this is the better filter to use here? 

Thanks for your help.  Here is my solution:

``` py
import pyvista as pv
from pyvista import examples
import numpy as np

pv.set_plot_theme('doc')

mesh = examples.download_kitchen()
furniture = examples.download_kitchen(split=True)

arr = np.linalg.norm(mesh['velocity'], axis=1)
clim = [arr.min(), arr.max()]

p = pv.Plotter()
p.add_mesh(furniture, name='furniture', color=True)
p.add_mesh(mesh.outline(), color='black')
p.add_axes()

points = [(0.3133218396043338, 2.7124684588348242, -0.1295403008931934),
          (6.141497065501868, 4.360221085241634, 1.1320318482460088)]

streamlines = mesh.streamlines(n_points=10, max_steps=100,
                            pointa=points[0], pointb=points[1],
                            integration_direction='forward')

p.add_mesh(streamlines, color='grey', show_scalar_bar=False)
#p.add_mesh(streamlines, scalars='IntegrationTime')

p.open_gif("streamlines.gif")

p.show(auto_close=False)

split_streamlines = streamlines.split_bodies()


nframes = 40
it_delta = 5

#- Range of 'IntegrationTime' for each individual streamline
it_ranges = [s.get_data_range(arr="IntegrationTime") for s in split_streamlines]
#- Maximum range of 'IntegrationTime' for all streamlines
it_range = streamlines.get_data_range(arr="IntegrationTime")

for it in np.linspace(it_range[0], it_range[1], nframes+1)[:nframes]:
    for s in range(split_streamlines.n_blocks):
        if it_ranges[s][0] <= it <= it_ranges[s][1]:
            itMin = max(it-it_delta, it_ranges[s][0])
            itMax = min(it+it_delta, it_ranges[s][1])

            clip = split_streamlines.get(s).clip_scalar(
                                        scalars='IntegrationTime',invert=False,
                                        value=itMin)
            clip = clip.clip_scalar(
                            scalars='IntegrationTime', value=itMax, invert=True
                            )

            p.add_mesh(clip,
                        scalars='velocity',clim=clim,
                        name='streamlines_threshold_'+str(s),
                        line_width=5, render_lines_as_tubes=True
            )
        else:
            p.remove_actor("streamlines_threshold_"+str(s))

    p.write_frame()

p.close()


```
![streamlines](https://user-images.githubusercontent.com/50269816/99161845-61221080-26c4-11eb-845e-8f944b522949.gif)

**Comment by hpenvern** [comment]
Hello,
I tried the above code as I would like to something similar with a result streamlines figure I have. Unfortunately, I get two error message :
1°/ TypeError: get_data_range() got an unexpected keyword argument 'arr'
I suppressed the "arr=" argument before "IntegrationTime" and it seemed to resolve the problem, but as I could not get tothe end...
2°/AttributeError: Render window is not available.
Indeed, I need to close the render window to get the code running, so it gives me this error when I get to "p.write_frame()" How do you manage to not close the render window... or have it open again but with the code running ? Maybe it has something to do with the open gif entry... I have never worked with this before so if you could explain to me newby... ^^
Thank you in advance for your answers.
