### ISSUE TITLE
AttributeError: BackgroundPlotter has no attribute named _add_observer

### ISSUE THREAD

**Issue by hanvisa** [pyvista/pyvista-support#422]
AttributeError: BackgroundPlotter has no attribute named _add_observer

## Description
I would like to simply use BackgroundPlotter via pyvistaqt. When running the example, the following error occurs.
It worked fine before, but after a fresh installation of anaconda, I can't run it. How do I solve this problem?

Python 3.8.8. This is a 64-bit environment.

Thanks for the help.

## Example Test code
import pyvista as pv
from pyvistaqt import BackgroundPlotter
sphere = pv.Sphere()
plotter = BackgroundPlotter()
plotter.add_mesh(sphere)
sphere.points *= 0.5

## Error
Traceback (most recent call last):
  File "c:\Users\hanvi\OneDrive\PY_Pyvista_pyvistaqt.py", line 6, in <module>
    plotter = BackgroundPlotter()
  File "C:\Users\hanvi\anaconda3\envs\f3dmap\lib\site-packages\pyvistaqt\plotting.py", line 631, in __init__                      r__
    super(BackgroundPlotter, self).__init__(
  File "C:\Users\hanvi\anaconda3\envs\f3dmap\lib\site-packages\pyvistaqt\plotting.py", line 259, in __init__
    self._add_observer("KeyPressEvent", self.key_press_event)
  File "C:\Users\hanvi\anaconda3\envs\f3dmap\lib\site-packages\vtkmodules\qt\QVTKRenderWindowInteractor.py", line 335, in __getattr__
    raise AttributeError(self.__class__.__name__ +
AttributeError: BackgroundPlotter has no attribute named _add_observer
![BackgroundPlotter_error](https://user-images.githubusercontent.com/84013743/117799372-fcb7c680-b28c-11eb-89e7-20aa258a7ff6.png)

**Comment by GuillaumeFavelier** [comment]
@hanvisa, now that `pyvistaqt 0.4.0` is released, you can update your version and try again. Looking forward to your feedback.

**Comment by hanvisa** [comment]
Tested and pyvistaqt now works again!:) Thanks!
