### ISSUE TITLE
Plotter will not update scalars

### ISSUE THREAD

**Issue by alexdaniilidis** [pyvista/pyvista-support#501]
Trying to update my plot with new scalars I came across a previous issue   ( [BackgroundPlotter not updating #68 ](https://github.com/pyvista/pyvista-support/issues/68)). I am able to reproduce the example there and the suggestions from @banesullivan (thanks!) and it works as intended on my workstation.

Trying to apply the same reasoning to my own model though (only data update), I can't get the plotter to update using pyvistaqt

```python
import pyvista as pv
import pyvistaqt as pvqt
import numpy as np
import time

cmap='viridis'    
nx,ny,nz = 60, 40, 42
nc = nx*ny*nz

np.random.seed(0)
inidata = np.random.randint(1, 100, nc)

# generate random data for updating
data = [np.random.randint(1, 1000, nc), 
        np.random.randint(1, 1e4, nc),
        np.random.randint(1, 1e5, nc),
        np.random.randint(1, 1e6, nc)]

gridata = np.ones((nx,ny,nz))

mesh = pv.UniformGrid()
mesh.dimensions = np.array(gridata.shape) + 1 


mesh.origin = (0, 0, 0)  # The bottom left corner of the data set
mesh.spacing = (30, 30, 2.5)  # These are the cell sizes along each axis

mesh.cell_arrays["Data"] = inidata

plotter = pvqt.BackgroundPlotter()

# Add slices
xslice = mesh.slice(normal='x')
yslice = mesh.slice(normal='y')
zslice = mesh.slice(normal='z')
rslice = mesh.slice(normal=[1,1,0])

# Plot
plotter.add_mesh(mesh.outline(), color="k")
plotter.add_mesh(xslice, cmap=cmap)
plotter.add_mesh(yslice, cmap=cmap)
plotter.add_mesh(zslice, cmap=cmap)
plotter.add_mesh(rslice, cmap=cmap)

def update():
    for dat in data:
        plotter.update_scalars(dat, mesh=mesh)
        time.sleep(1)
        plotter.update()
        
plotter.add_callback(update, interval=100)
```

**Comment by akaszynski** [comment]
The solution is to update the scalars in a different thread:
```py
from pyvista.utilities import threaded

@threaded
def update():
    for dat in data:
        plotter.update_scalars(dat, mesh=mesh)
        time.sleep(1)
        plotter.update()

plotter.add_callback(update, interval=100)
```

I'm still not convinced this is the best approach since these should be updating already, but this will at least work.

**Comment by alexdaniilidis** [comment]
@akaszynski thanks for the suggestion. I tried it and the result remains that my plot is not updated.

Could it be that I should be using a different function than `update_scalars`  to update data or something other than `cell_arrays` to assign initial values?

**Comment by akaszynski** [comment]
I think that might be it.  What I'd do instead is first setup scalars with:
```
mesh['scalars'] = scalars
```

Then overwrite them in your update method with:

```
mesh['scalars'][:] = scalars
```

You may have to trigger a render at the end of the update method with `plotter.render` if they are not updated immediately after overwriting them in situ.

**Comment by alexdaniilidis** [comment]
thanks for the suggestion. This seems to do some update but it is not consistent. The plot shows any of the datasets (initial, middle or last) but it is not updating after sleeping. The resulting figure is static.
Any thoughts?

**Comment by alexdaniilidis** [comment]
@akaszynski any other ideas on what could be going wrong here?

**Comment by leminhson** [comment]
In my opinion, we should place the sections of #"Add Slices" and "#Plot" inside of the function update() to refresh the slices.

However, the scalar_bar_range will not update if the data range is smaller than the scalar_bar_range even though we force to update by `plotter.update_scalar_bar_range()`.

Therefore we have to refresh scalar_bar_range manually.

```
def update():
    for dat in data:
        # Add slices
        plotter.update_scalars(dat, mesh=mesh)
        xslice = mesh.slice(normal='x')
        yslice = mesh.slice(normal='y')
        zslice = mesh.slice(normal='z')
        rslice = mesh.slice(normal=[1, 1, 0])

        # Plot
        plotter.add_mesh(xslice, cmap=cmap)
        plotter.add_mesh(yslice, cmap=cmap)
        plotter.add_mesh(zslice, cmap=cmap)
        plotter.add_mesh(rslice, cmap=cmap)
        plotter.add_mesh(mesh.outline(), color="k")
        time.sleep(1)
    plotter.scalar_bars._scalar_bar_ranges = {mesh.active_scalars_name: [0, 0]}
```

**Comment by alexdaniilidis** [comment]
thanks @leminhson for the suggestion.

this seems to work for me. It looks a bit weird though and things update slowly. I can see each slice being updated kind of in slow motion.

I also get a wall of errors like this one:
```python
Exception in thread Thread-202:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\PyVista_updating.py", line 98, in update
    # plotter.add_mesh(rslice, cmap=cmap)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvista\plotting\plotting.py", line 1649, in add_mesh
    prepare_mapper(scalars)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvista\plotting\plotting.py", line 1635, in prepare_mapper
    self.mesh.cell_arrays.append(scalars, title, True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvista\core\datasetattributes.py", line 205, in append
    raise ValueError(f'narray length of ({narray.shape[0]}) != required length ({array_len})')
ValueError: narray length of (1680) != required length (2400)
```
Quite puzzled why this is so difficult

**Comment by leminhson** [comment]
@alexdaniilidis : I can run that code without any error. Here is an animated gif of the screen:
![data_update](https://user-images.githubusercontent.com/14102005/135546805-009b6b3a-dfaa-4083-9fb8-87b1825833e3.gif)

Based on the error, we have a problem when adding a `rslice `mesh because of the wrong size 1680 instead of 2400. However, '2400' is the length of `zslice`, not of `rslice`. I have no idea why it required the value of 2400 ???

I think we should wait for the comments from the other experts on pyvista.

Here is the code I used for the image above:
```
import pyvista as pv
import pyvistaqt as pvqt
import numpy as np
import time

cmap = 'viridis'
nx, ny, nz = 60, 40, 42
nc = nx*ny*nz

np.random.seed(0)
inidata = np.random.randint(1, 100, nc)

# generate random data for updating
data = [np.random.randint(1, 1000, nc),
        np.random.randint(1, 1e4, nc),
        np.random.randint(1, 1e5, nc),
        np.random.randint(1, 1e6, nc)]

gridata = np.ones((nx, ny, nz))

mesh = pv.UniformGrid()
mesh.dimensions = np.array(gridata.shape) + 1

mesh.origin = (0, 0, 0)  # The bottom left corner of the data set
mesh.spacing = (30, 30, 2.5)  # These are the cell sizes along each axis

mesh.cell_arrays["Data"] = inidata

plotter = pvqt.BackgroundPlotter()

def update():
    for dat in data:
        # Add slices
        plotter.update_scalars(dat, mesh=mesh)
        xslice = mesh.slice(normal='x')
        yslice = mesh.slice(normal='y')
        zslice = mesh.slice(normal='z')
        rslice = mesh.slice(normal=[1, 1, 0])

        # Plot
        plotter.add_mesh(xslice, cmap=cmap)
        plotter.add_mesh(yslice, cmap=cmap)
        plotter.add_mesh(zslice, cmap=cmap)
        plotter.add_mesh(rslice, cmap=cmap)
        plotter.add_mesh(mesh.outline(), color="k")

        time.sleep(1)
    plotter.scalar_bars._scalar_bar_ranges = {mesh.active_scalars_name: [0, 0]}

plotter.add_callback(update, interval=100)
plotter.app.exec_()

**Comment by alexdaniilidis** [comment]
thanks @leminhson  for the update. Your gif seems to be working great though and does what is expected.

Here is a gif of what I see running your exact code from above
![PyVistUpdate](https://user-images.githubusercontent.com/34479636/135639341-3af599cf-0598-4f63-9ffa-428d5cfddf4e.gif)
:


Input from pyvista experts would be great indeed

**Comment by leminhson** [comment]
@alexdaniilidis :
The purple color is due to the scalar_bar is not refresed when `dat` is changed.
And you could see in your gif, the scalar bar is not updated when dat is changed.

Could you check the command:
`plotter.scalar_bars._scalar_bar_ranges = {mesh.active_scalars_name: [0, 0]}` is outside the for loop ?

**Comment by alexdaniilidis** [comment]
@leminhson ```python plotter.scalar_bars._scalar_bar_ranges = {mesh.active_scalars_name: [0, 0]}```    is indeed outside the for loop. My run was a direct copy of the code you provided

**Comment by vpicouet** [comment]
Hello,
I have a similar problem.
In the code below that you can run, update_scalars only updates the point cloud, the StructuredGrid mesh scalar seems to change but they are way of the colorbar eventhough I verified that the values are within it...
So the first run is ok, but as soon as I click the checkbox, the mesh as a wrong color (see image)
Would you have any idea what I am doing wrong here?
Thanks a lot

```python


def fit_surface(x,y,z):
    import scipy
    data = np.array([x,y,z]).T

    # regular grid covering the domain of the data
    n=50
    X,Y = np.meshgrid(np.arange(x.min(),x.max(), n), np.arange(y.min(),y.max(),n))
    XX = X.flatten()
    YY = Y.flatten()
    order = 2    # 1: linear, 2: quadratic
    if order == 1:
        # best-fit linear plane
        A = np.c_[data[:,0], data[:,1], np.ones(data.shape[0])]
        C,_,_,_ = scipy.linalg.lstsq(A, data[:,2])    # coefficients
        # evaluate it on grid
        Z = C[0]*X + C[1]*Y + C[2]
        # or expressed using matrix/vector product
        #Z = np.dot(np.c_[XX, YY, np.ones(XX.shape)], C).reshape(X.shape)
    elif order == 2:
        # best-fit quadratic curve
        A = np.c_[np.ones(data.shape[0]), data[:,:2], np.prod(data[:,:2], axis=1), data[:,:2]**2]
        C,_,_,_ = scipy.linalg.lstsq(A, data[:,2])
        # evaluate it on a grid
        Z = np.dot(np.c_[np.ones(XX.shape), XX, YY, XX*YY, XX**2, YY**2], C).reshape(X.shape)
    return  np.array(X, dtype=np.float32), np.array(Y, dtype=np.float32), np.array(Z, dtype=np.float32)



def plot_surface(cat,x_,y_,z_):
    from pyvista import Plotter, set_plot_theme  # StructuredGrid, PolyData,
    import pyvista as pv
    import numpy as np
    zz = (cat[z_]-cat[z_].min())/(cat[z_]-cat[z_].min()).ptp()
    X,Y,Z = fit_surface(cat[x_],cat[y_],zz)
    data = np.array([cat[x_],cat[y_],zz]).T

    set_plot_theme("document")
    # Create and plot structured grid
    mesh = pv.StructuredGrid(X, Y,Z)# (z-z.min()/(z-z.min().ptp()))
    mesh_non_normalized =  pv.StructuredGrid(*fit_surface(cat[x_],cat[y_],cat[z_]))
    p = Plotter(
        notebook=False,
        window_size=(1500, 1000),
        line_smoothing=True,
        point_smoothing=True,
        polygon_smoothing=True,
        splitting_position=None,
    )
    cmap='jet'
    names = [c for c in cat.colnames]*50
    dict_ = {"field": z_}
    p.add_title(z_)
    p.show_grid()
    mesh['scalars'] = mesh_non_normalized.points[:, -1]#,scalars='scalars',#
    p.add_mesh(mesh,show_edges=True, scalars=mesh_non_normalized.points[:, -1],
              scalar_bar_args={'vertical': True}   ,lighting=False,opacity=0.7  ,
              use_transparency=False,  cmap=cmap)
    p.set_scale(xscale=1, yscale=1, zscale=0.7*cat[x_].ptp()/zz.ptp())
    point_cloud = pv.PolyData(data)
    point_cloud['scalars'] =cat[z_]
    p.add_points(data,render_points_as_spheres=True,point_size=30.0,  cmap=cmap, scalars=cat[z_],)

    def change_field(val):
        a=cat
        index = names.index(dict_["field"])
        name = names[index + 1]
        dict_["field"] = name
        points = mesh.points.copy()
        value = (a[name] - a[name].min())/ (a[name] - a[name].min()).ptp()
        data[:, -1] = value#(value - np.nanmin(value)).reshape(-1)#value * 
        p.update_coordinates(data,render=False)#,mesh=point_cloud
        scalar = a[name].ravel()
        p.update_scalars(scalar,  render=False)# mesh=point_cloud,
        _ =pv.StructuredGrid(*fit_surface(cat[x_],cat[y_],cat[name] ))
        mesh['scalars'] = _.points[:, -1].ravel()
        p.update_coordinates(pv.StructuredGrid(*fit_surface(cat[x_],cat[y_],value)).points, mesh=mesh,render=False)
        p.update_scalars(_.points[:, -1].ravel(), mesh=mesh, render=True)
        p.add_title(name + ": %0.1f,%0.1f"%(np.nanmin(_.points[:, -1]), np.nanmax(_.points[:, -1])))
        # p.add_title(name + ": %0.1f,%0.1f"%(np.nanmin(scalar), np.nanmax(scalar)))
        p.update_scalar_bar_range([np.nanmin(scalar), np.nanmax(scalar)])
        # p.update_scalar_bar_range([np.nanmin(_.points[:, -1]), np.nanmax(_.points[:, -1])])
        # p.update_scalar_bar_range([np.nanmin(mesh_non_normalized.points[:, -1]), np.nanmax(mesh_non_normalized.points[:, -1])], mesh=mesh)
        # p.update_coordinates(data)  # , render=False)
        p.scalar_bars._scalar_bar_ranges = {mesh.active_scalars_name: [0, 0]}
        plotter.render()

    p.add_checkbox_button_widget(change_field, position=(10, 150))
    p.show()

cat=Table.read('fwhm.csv')
plot_surface(cat,x_='x',y_='y',z_='amplitude')
```

![Enregistrement d’écran, le 2022-04-27 à 14 24 30 mov](https://user-images.githubusercontent.com/37241971/165594294-d326a286-2b34-40a7-8b1d-3eb61e795c40.gif)

[fwhm.csv](https://github.com/pyvista/pyvista-support/files/8575259/fwhm.csv)
